sudo: required
language: c++
service:
  - docker
before_install:
  - docker pull velocitymonb/xcompiler-qt5-ubuntu-raspberrypi

os: linux

env: 
osglobal:
  matrix:
    - QTRPI_VERSION=qt5.9
    - QTRPI_VERSION=qt5.qt10
    - QTRPI_VERSION=qt5.13
jobs:
  include:
    - stage: build
    - script:  | 
        printenv
        ls -la 
        /bin/bash -c examplebash.sh
