version: 2

#------------------------------------------------------------------------------        
workflows:
  version: 2
  default:
    jobs:
      - run-prepare-image
        #
# TODO: prepare this one
#      - clone-CrossCompiler
#      - run-Crosscompiler  
#------------------------------------------------------------------------------        
jobs:
#------------------------------------------------------------------------------        
  run-prepare-image:
    docker:
      - image: ubuntu:18.04
    enviroment:
    build:
      branches:
        ignore:
          - develop
          - /feature-.*/
    steps:
      - checkout
      - run:
          name: Greeting
          command: |
            echo Running CrossCompiler
            set +e
            apt update && apt upgrade
            apt install curl wget git cmake -y
            pwd
            git clone https://github.com/gpmontt/CrossCompilerRpi3QT5
            cd CrossCompilerRpi3QT5
            cd qt5pibuilder
            bash ./build




