version: 2

references:
  workspace_root: &workspace_root
     /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

#------------------------------------------------------------------------------        
workflows:
  version: 2
  default:
    jobs:
      - run-prepare-image
      - publish-github-release:
          requires:
            - run-prepare-image


# TODO: prepare this one
#      - run-Crosscompiler  
#------------------------------------------------------------------------------        
jobs:
#------------------------------------------------------------------------------        
  run-prepare-image:
    docker:
      - image: earmadilo/xcompiler.qt59.gcc730

    enviroment:
    build:
      branches:
        only: 
          - master
          - /rc-.*/  
        ignore:
          - develop
          - /feature-.*/

    resource_class: medium
    
    steps:
      - checkout
      - run:
          name: building crosscompiler
          command: |
            set +e
            echo Running CrossCompiler
            pwd
            mv /root/project/qt5pibuilder /opt/
            cd /opt/qt5pibuilder
            bash ./build
            cd ..
            ls
            zip -r /opt/qt5pibuilder.zip qt5pibuilder/qt5
            zip -r /opt/qt5pibuilder.zip qt5pibuilder/qt5pi
            ls -lah /
            #echo print temporal file under /tmp
      - persist_to_workspace:
          root: *workspace_root
          paths: 
            - qt5pibuilder.zip
             


  publish-github-release:
    docker:
      - image: circleci/golang:1.8   
    steps:
      - *attach_workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ls -liah /tmp/workspace
            export CIRCLE_TAG='v1.1' 
            echo "CIRCLE_TAG=${CIRCLE_TAG}"
            echo "GITHUB_TOKEN=${GITHUB_TOKEN}"
            echo "CIRCLE_PROJECT_USERNAME=${CIRCLE_PROJECT_USERNAME}"
            echo "CIRCLE_PROJECT_REPONAME=${CIRCLE_PROJECT_REPONAME}"
            echo "CIRCLE_SHA1=${CIRCLE_SHA1}"
            VERSION=file_$(date +%Y-%m-%d)
            echo "VERSION=${VERSION}"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete -replace $VERSION$TAG  /tmp/workspace/qt5pibuilder.zip
