version: 2

#------------------------------------------------------------------------------        
workflows:
  version: 2
  default:
    jobs:
      - run-prepare-image
        #
# TODO: prepare this one
#      - clone-CrossCompiler
#      - run-Crosscompiler  
#------------------------------------------------------------------------------        
jobs:
#------------------------------------------------------------------------------        
  run-prepare-image:
    docker:
      - image: ubuntu:18.04
    enviroment:
    build:
      branches:
        ignore:
          - develop
          - /feature-.*/
    steps:
      - checkout
      - run:
          name: Greeting
          command: |
            echo Running CrossCompiler
            set +e
            pwd
            ls
            echo update file add apt\/source
            apt update && apt-get update && apt-get install -y build-essential\
            wget curl git cmake python xz-utils  && rm -rf /var/lib/apt/lists/*
            git clone https://github.com/gpmontt/CrossCompilerRpi3QT5
            ls -lah
            cd CrossCompilerRpi3QT5
            cd qt5pibuilder
            bash ./build




