version: 2

references:
  workspace_root: &workspace_root
    /tmp
    
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

#------------------------------------------------------------------------------        
workflows:
  version: 2
  default:
    jobs:
      - run-prepare-image
      - publish-github-release:
          requires:
            - run-prepare-image


# TODO: prepare this one
#      - run-Crosscompiler  
#------------------------------------------------------------------------------        
jobs:
#------------------------------------------------------------------------------        
  run-prepare-image:
    docker:
      - image: gpmontt/dockertutorialinstallation

    enviroment:
    working_directory: ~/project_folder
    
    build:
      branches:
        only: 
          - master
          - /rc-.*/  
        ignore:
          - develop
          - /feature-.*/

    resource_class: medium

    steps:
      - checkout
      - run:
          name: building crosscompiler
          command: |
            set +e
            echo Running CrossCompiler
            apt-get update && rm -rf /var/lib/apt/lists/*
            ls -lah
            #cd qt5pibuilder
            #bash ./build
            ls -lah /tmp
            #echo print temporal file under /tmp
      - persist_to_workspace:
          root: *workspace_root
          paths: 
            - qt5pibuilder
            - examplebash.sh          
             


  publish-github-release:
    docker:
      - image: circleci/golang:1.8   
    steps:
      - *attach_workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ls -liah /tmp 
            echo "CIRCLE_TAG=${CIRCLE_TAG}"
            echo "GITHUB_TOKEN=${GITHUB_TOKEN}"
            echo "CIRCLE_PROJECT_USERNAME=${CIRCLE_PROJECT_USERNAME}"
            echo "CIRCLE_PROJECT_REPONAME=${CIRCLE_PROJECT_REPONAME}"
            echo "CIRCLE_SHA1=${CIRCLE_SHA1}"
            VERSION=file_$(date +%Y-%m-%d)
            echo "VERSION=${VERSION}"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete -replace $VERSION$TAG  /tmp/examplebash.sh

            
  
